language: java
jdk:
  - oraclejdk7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "mvn clean verify -f f4tests/pom.xml"
install: "mvn clean verify -DskipTests=true"
